# Generated by Django 2.1 on 2018-09-14 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone number')),
                ('emailP', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('pid', models.CharField(max_length=10)),
                ('pwd', models.IntegerField()),
            ],
        ),
    ]
