# Generated by Django 2.1 on 2018-09-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='id',
        ),
        migrations.AlterField(
            model_name='parent',
            name='pid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
