# Generated by Django 2.1 on 2018-09-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_student_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='pid',
            new_name='puname',
        ),
        migrations.AlterField(
            model_name='student',
            name='pid',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='webapp.Parent', to_field='pid'),
        ),
    ]
