# Generated by Django 2.1 on 2018-09-15 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180915_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pid',
        ),
        migrations.AddField(
            model_name='student',
            name='puname',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='webapp.Parent'),
        ),
    ]
