# Generated by Django 2.1 on 2018-09-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180915_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='pwd',
            field=models.CharField(max_length=100),
        ),
    ]
