# Generated by Django 2.1 on 2018-09-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180915_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='puname',
            new_name='puname_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='puname',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='webapp.Parent', to_field='puname'),
        ),
    ]
