# Generated by Django 2.1 on 2018-09-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180915_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='puname',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
