# Generated by Django 2.1 on 2018-09-15 05:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180915_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone number')),
                ('emailP', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('puname', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone number')),
                ('emailP', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('dept', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('puname', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='webapp.Parent')),
            ],
        ),
    ]
