# Generated by Django 2.1 on 2018-09-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_parent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptId', models.IntegerField(default=0)),
                ('deptName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
