# Generated by Django 2.1 on 2018-09-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='div',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_id',
            field=models.CharField(default='CUG1', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
