# Generated by Django 2.1 on 2018-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20180917_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
