# Generated by Django 2.1 on 2018-09-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20180917_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('sem', models.IntegerField(default=1)),
                ('subj', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=2)),
                ('isExam', models.IntegerField(default=0)),
                ('teacher_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='webapp.Teacher')),
            ],
        ),
    ]
