# Generated by Django 2.1 on 2018-09-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_teacher_teacherresp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherresp',
            old_name='teacher_id',
            new_name='teachId',
        ),
    ]
