# Generated by Django 2.1 on 2018-09-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20180917_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='teacherId',
        ),
        migrations.AlterField(
            model_name='teacherresp',
            name='teachId',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='webapp.Teacher', to_field='teacher_id'),
        ),
    ]
