# Generated by Django 2.1 on 2018-09-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_remove_teacherresp_teachid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherresp',
            name='teachId',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='webapp.Teacher'),
        ),
    ]
