# Generated by Django 2.1 on 2018-09-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_teacherresp_teachid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherresp',
            name='teachId',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='TeacherResp',
        ),
    ]
