# Generated by Django 2.1 on 2018-09-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_teacher_teacherresp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherresp',
            old_name='teachId',
            new_name='teacher',
        ),
    ]
