# Generated by Django 2.1 on 2018-09-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20180917_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='studMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examid', models.CharField(max_length=10)),
                ('marks', models.IntegerField(blank=True, default=0, null=True)),
                ('roll', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='webapp.Student')),
            ],
        ),
    ]
