# Generated by Django 2.1 on 2018-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_studmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studmarks',
            name='examid',
            field=models.CharField(max_length=50),
        ),
    ]
