# Generated by Django 2.1 on 2018-09-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_remove_student_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('lecId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('roll', models.CharField(max_length=10)),
                ('curratt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
