# Generated by Django 2.1 on 2018-09-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
