# Generated by Django 2.1 on 2018-09-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('eid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('courseId', models.CharField(max_length=10)),
                ('subj', models.CharField(max_length=50)),
                ('sem', models.IntegerField(default=0)),
                ('div', models.CharField(max_length=1)),
                ('doexam', models.DateField()),
            ],
        ),
    ]
