# Generated by Django 2.1 on 2018-09-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.IntegerField(default=0)),
                ('isUpdated', models.BinaryField(max_length=1)),
                ('isPresent', models.BinaryField(max_length=1)),
                ('eid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.Exam')),
            ],
        ),
    ]
