# Generated by Django 2.1 on 2018-09-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='doexam',
            field=models.DateField(default='2018-09-19'),
        ),
    ]
