# Generated by Django 2.1 on 2018-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_auto_20180919_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('isPresent', models.IntegerField(default=0)),
                ('course', models.CharField(default='0', max_length=10)),
                ('roll', models.CharField(default='0', max_length=10)),
                ('subject', models.CharField(default='0', max_length=50)),
            ],
        ),
    ]
