# Generated by Django 2.1 on 2018-09-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_dailyattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deptId',
            field=models.IntegerField(default=1),
        ),
    ]
